"""
Copyright (c) Cutleast
"""

import pprint
import shutil
import sys
from pathlib import Path
from typing import Any, Optional, override

from cutleast_core_lib.core.utilities.process_runner import run_process

from ..build_backend import BuildBackend
from ..build_metadata import BuildMetadata


class PyInstallerBackend(BuildBackend):
    """
    PyInstaller backend implementation.

    **Requires `PyInstaller` to be installed in the project's environment!**
    """

    def get_additional_analysis_options(
        self,
        main_module: Path,
        exe_stem: str,
        icon_path: Optional[Path],
        metadata: BuildMetadata,
    ) -> dict[str, Any]:
        """Returns additional backend-specific `Analysis` options."""

        return {}

    def get_additional_exe_options(
        self,
        main_module: Path,
        exe_stem: str,
        icon_path: Optional[Path],
        metadata: BuildMetadata,
    ) -> dict[str, Any]:
        """Returns additional options shared by both `EXE` targets."""

        return {}

    def get_additional_collect_options(
        self,
        main_module: Path,
        exe_stem: str,
        icon_path: Optional[Path],
        metadata: BuildMetadata,
    ) -> dict[str, Any]:
        """Returns additional backend-specific `COLLECT` options."""

        return {}

    @override
    def build(
        self,
        main_module: Path,
        exe_stem: str,
        icon_path: Optional[Path],
        metadata: BuildMetadata,
    ) -> Path:
        output_root: Path = Path.cwd() / f"{main_module.stem}.pyinstaller-build"
        shutil.rmtree(output_root, ignore_errors=True)
        output_root.mkdir(parents=True)

        analysis_options: dict[str, Any] = {
            "pathex": [str(main_module.parent)],
            "excludes": ["tkinter", "unittest"],
        }
        exe_options: dict[str, Any] = {}
        collect_options: dict[str, Any] = {}
        self.__merge_options(
            analysis_options,
            self.get_additional_analysis_options(
                main_module, exe_stem, icon_path, metadata
            ),
            {"scripts"},
        )
        self.__merge_options(
            exe_options,
            self.get_additional_exe_options(main_module, exe_stem, icon_path, metadata),
            {"console", "exclude_binaries", "icon", "name"},
        )
        self.__merge_options(
            collect_options,
            self.get_additional_collect_options(
                main_module, exe_stem, icon_path, metadata
            ),
            {"name"},
        )

        spec_path: Path = output_root / "build.spec"
        icon: Optional[str] = str(icon_path.resolve()) if icon_path else None
        spec_path.write_text(
            self.__get_spec(
                main_module.resolve(),
                exe_stem,
                icon,
                analysis_options,
                exe_options,
                collect_options,
            ),
            encoding="utf8",
        )

        dist_root: Path = output_root / "dist"
        cmd: list[str] = [
            sys.executable,
            "-m",
            "PyInstaller",
            "--noconfirm",
            f"--distpath={dist_root}",
            f"--workpath={output_root / 'work'}",
            str(spec_path),
        ]
        self.log.info(f"Running PyInstaller command: '{' '.join(cmd)}'...")
        run_process(cmd, live_output=True)

        return dist_root / "output"

    @staticmethod
    def __merge_options(
        options: dict[str, Any],
        additional_options: dict[str, Any],
        protected_options: set[str],
    ) -> None:
        """Merges backend-specific options without changing the output contract."""

        invalid_options: set[str] = additional_options.keys() & protected_options
        if invalid_options:
            names: str = ", ".join(sorted(invalid_options))
            raise ValueError(f"Cannot override PyInstaller option(s): {names}")

        for option, value in additional_options.items():
            if isinstance(value, list):
                options.setdefault(option, []).extend(value)
            else:
                options[option] = value

    @staticmethod
    def __get_spec(
        main_module: Path,
        exe_stem: str,
        icon_path: Optional[str],
        analysis_options: dict[str, Any],
        exe_options: dict[str, Any],
        collect_options: dict[str, Any],
    ) -> str:
        """Creates a spec with one shared analysis and two executable targets."""

        return f"""# Generated by cutleast-core-lib.
analysis = Analysis([{str(main_module)!r}], **{pprint.pformat(analysis_options)})
pyz = PYZ(analysis.pure)

gui_exe = EXE(
    pyz, analysis.scripts, [], exclude_binaries=True,
    name={exe_stem!r}, console=False, icon={icon_path!r},
    **{pprint.pformat(exe_options)},
)
cli_exe = EXE(
    pyz, analysis.scripts, [], exclude_binaries=True,
    name={f"{exe_stem}_cli"!r}, console=True, icon={icon_path!r},
    **{pprint.pformat(exe_options)},
)

COLLECT(
    gui_exe, cli_exe, analysis.binaries, analysis.datas,
    name="output", **{pprint.pformat(collect_options)},
)
"""

    @override
    def clean(self, main_module: Path, exe_stem: str) -> None:
        shutil.rmtree(
            Path.cwd() / f"{main_module.stem}.pyinstaller-build", ignore_errors=True
        )
